[project]
name = "pantokrator-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Badsha1996", email = "badshalaskar96@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "textual==8.2.8",
    "textual-dev>=1.8.0",
]

[project.scripts]
pantokrator-ai = "src:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
# the package *is* src/ — no nested pantokrator_ai/ dir
module-root = ""
module-name = "src"
